# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /bluearc/storage/recon/devel/code/jartracker

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /coupp/data/home/coupp/recon/devel/code/jartracker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /coupp/data/home/coupp/recon/devel/code/jartracker/CMakeFiles /coupp/data/home/coupp/recon/devel/code/jartracker/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /coupp/data/home/coupp/recon/devel/code/jartracker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named P60Optometrist

# Build rule for target.
P60Optometrist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 P60Optometrist
.PHONY : P60Optometrist

# fast build rule for target.
P60Optometrist/fast:
	$(MAKE) -f CMakeFiles/P60Optometrist.dir/build.make CMakeFiles/P60Optometrist.dir/build
.PHONY : P60Optometrist/fast

P60OptometristStart.o: P60OptometristStart.cpp.o
.PHONY : P60OptometristStart.o

# target to build an object file
P60OptometristStart.cpp.o:
	$(MAKE) -f CMakeFiles/P60Optometrist.dir/build.make CMakeFiles/P60Optometrist.dir/P60OptometristStart.cpp.o
.PHONY : P60OptometristStart.cpp.o

P60OptometristStart.i: P60OptometristStart.cpp.i
.PHONY : P60OptometristStart.i

# target to preprocess a source file
P60OptometristStart.cpp.i:
	$(MAKE) -f CMakeFiles/P60Optometrist.dir/build.make CMakeFiles/P60Optometrist.dir/P60OptometristStart.cpp.i
.PHONY : P60OptometristStart.cpp.i

P60OptometristStart.s: P60OptometristStart.cpp.s
.PHONY : P60OptometristStart.s

# target to generate assembly for a file
P60OptometristStart.cpp.s:
	$(MAKE) -f CMakeFiles/P60Optometrist.dir/build.make CMakeFiles/P60Optometrist.dir/P60OptometristStart.cpp.s
.PHONY : P60OptometristStart.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... P60Optometrist"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... P60OptometristStart.o"
	@echo "... P60OptometristStart.i"
	@echo "... P60OptometristStart.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

